{% set name = "types-psutil" %}
{% set version = "7.0.0.20250516" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types_psutil-{{ version }}.tar.gz
  sha256: 3d8aa8392ac4d1e5e9237d111cf9e59d8fce8f2bde3115e687623f5e1039a1ab

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
  run:
    - python

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for psutil
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mr-c